### ISSUE TITLE
Internet Explorer Issues

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/valerie-bordeleau#1]
@thomasjbradley

Hey Thomas, 
I'm still having issues with internet explorer duplicating the back arrow on my projects page as well as extra space beneath the footer,

Thanks

**Comment by thomasjbradley** [comment]
It looks like the SVG just needs an overflow hidden on it, try adding this to your CSS:

``` css
svg:not(:root) {
  overflow: hidden;
}
```
